// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPersonRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPersonRequest) Reset()         { *m = GetPersonRequest{} }
func (m *GetPersonRequest) String() string { return proto.CompactTextString(m) }
func (*GetPersonRequest) ProtoMessage()    {}
func (*GetPersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *GetPersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonRequest.Unmarshal(m, b)
}
func (m *GetPersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonRequest.Marshal(b, m, deterministic)
}
func (m *GetPersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonRequest.Merge(m, src)
}
func (m *GetPersonRequest) XXX_Size() int {
	return xxx_messageInfo_GetPersonRequest.Size(m)
}
func (m *GetPersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonRequest proto.InternalMessageInfo

func (m *GetPersonRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPersonResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPersonResponse) Reset()         { *m = GetPersonResponse{} }
func (m *GetPersonResponse) String() string { return proto.CompactTextString(m) }
func (*GetPersonResponse) ProtoMessage()    {}
func (*GetPersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *GetPersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonResponse.Unmarshal(m, b)
}
func (m *GetPersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonResponse.Marshal(b, m, deterministic)
}
func (m *GetPersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonResponse.Merge(m, src)
}
func (m *GetPersonResponse) XXX_Size() int {
	return xxx_messageInfo_GetPersonResponse.Size(m)
}
func (m *GetPersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonResponse proto.InternalMessageInfo

func (m *GetPersonResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetPersonResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPersonResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetPersonsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPersonsRequest) Reset()         { *m = GetPersonsRequest{} }
func (m *GetPersonsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPersonsRequest) ProtoMessage()    {}
func (*GetPersonsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{2}
}

func (m *GetPersonsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonsRequest.Unmarshal(m, b)
}
func (m *GetPersonsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonsRequest.Marshal(b, m, deterministic)
}
func (m *GetPersonsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonsRequest.Merge(m, src)
}
func (m *GetPersonsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPersonsRequest.Size(m)
}
func (m *GetPersonsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonsRequest proto.InternalMessageInfo

type GetPersonsResponse struct {
	Persons              []*GetPersonResponse `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetPersonsResponse) Reset()         { *m = GetPersonsResponse{} }
func (m *GetPersonsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPersonsResponse) ProtoMessage()    {}
func (*GetPersonsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{3}
}

func (m *GetPersonsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonsResponse.Unmarshal(m, b)
}
func (m *GetPersonsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonsResponse.Marshal(b, m, deterministic)
}
func (m *GetPersonsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonsResponse.Merge(m, src)
}
func (m *GetPersonsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPersonsResponse.Size(m)
}
func (m *GetPersonsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonsResponse proto.InternalMessageInfo

func (m *GetPersonsResponse) GetPersons() []*GetPersonResponse {
	if m != nil {
		return m.Persons
	}
	return nil
}

func init() {
	proto.RegisterType((*GetPersonRequest)(nil), "v1.GetPersonRequest")
	proto.RegisterType((*GetPersonResponse)(nil), "v1.GetPersonResponse")
	proto.RegisterType((*GetPersonsRequest)(nil), "v1.GetPersonsRequest")
	proto.RegisterType((*GetPersonsResponse)(nil), "v1.GetPersonsResponse")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x94, 0x92, 0x49, 0xcf,
	0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c,
	0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0xa8, 0x50, 0x52, 0xe2, 0x12, 0x70, 0x4f, 0x2d, 0x09, 0x00, 0x6b,
	0x0a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x51, 0xf2, 0xe5, 0x12, 0x44, 0x52, 0x53, 0x5c, 0x90,
	0x9f, 0x57, 0x9c, 0x8a, 0xae, 0x48, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x09,
	0x2c, 0x02, 0x66, 0x0b, 0x89, 0x70, 0xb1, 0xa6, 0xe6, 0x26, 0x66, 0xe6, 0x48, 0x30, 0x83, 0x05,
	0x21, 0x1c, 0x25, 0x61, 0x24, 0xe3, 0x8a, 0xa1, 0x76, 0x2a, 0xb9, 0x72, 0x09, 0x21, 0x0b, 0x42,
	0x2d, 0xd1, 0xe7, 0x62, 0x87, 0xf8, 0xa7, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x54,
	0xaf, 0xcc, 0x50, 0x0f, 0xc3, 0x31, 0x41, 0x30, 0x55, 0x46, 0xcb, 0x18, 0xb9, 0xd8, 0x20, 0x72,
	0x42, 0x7e, 0x5c, 0x9c, 0x70, 0x85, 0x42, 0x22, 0x68, 0xfa, 0xc0, 0x96, 0x4a, 0x61, 0x37, 0x4d,
	0x49, 0xa4, 0xe9, 0xf2, 0x93, 0xc9, 0x4c, 0x7c, 0x42, 0x3c, 0xfa, 0x10, 0x63, 0xf5, 0xab, 0x33,
	0x53, 0x6a, 0x85, 0x7c, 0xb8, 0xb8, 0x10, 0x2e, 0x14, 0x42, 0xd5, 0x0a, 0xf3, 0x86, 0x94, 0x18,
	0xba, 0x30, 0xd4, 0x48, 0x7e, 0xb0, 0x91, 0x9c, 0x42, 0xec, 0x50, 0x23, 0x9d, 0xd8, 0xa2, 0x58,
	0xf4, 0xac, 0xcb, 0x0c, 0x93, 0xd8, 0xc0, 0xd1, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x1c,
	0xa0, 0xb6, 0xc6, 0xb8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonClient is the client API for Person service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonClient interface {
	GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error)
	GetPersons(ctx context.Context, in *GetPersonsRequest, opts ...grpc.CallOption) (*GetPersonsResponse, error)
}

type personClient struct {
	cc *grpc.ClientConn
}

func NewPersonClient(cc *grpc.ClientConn) PersonClient {
	return &personClient{cc}
}

func (c *personClient) GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error) {
	out := new(GetPersonResponse)
	err := c.cc.Invoke(ctx, "/v1.Person/GetPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personClient) GetPersons(ctx context.Context, in *GetPersonsRequest, opts ...grpc.CallOption) (*GetPersonsResponse, error) {
	out := new(GetPersonsResponse)
	err := c.cc.Invoke(ctx, "/v1.Person/GetPersons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonServer is the server API for Person service.
type PersonServer interface {
	GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error)
	GetPersons(context.Context, *GetPersonsRequest) (*GetPersonsResponse, error)
}

// UnimplementedPersonServer can be embedded to have forward compatible implementations.
type UnimplementedPersonServer struct {
}

func (*UnimplementedPersonServer) GetPerson(ctx context.Context, req *GetPersonRequest) (*GetPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerson not implemented")
}
func (*UnimplementedPersonServer) GetPersons(ctx context.Context, req *GetPersonsRequest) (*GetPersonsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersons not implemented")
}

func RegisterPersonServer(s *grpc.Server, srv PersonServer) {
	s.RegisterService(&_Person_serviceDesc, srv)
}

func _Person_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Person/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServer).GetPerson(ctx, req.(*GetPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Person_GetPersons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServer).GetPersons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Person/GetPersons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServer).GetPersons(ctx, req.(*GetPersonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Person_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Person",
	HandlerType: (*PersonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _Person_GetPerson_Handler,
		},
		{
			MethodName: "GetPersons",
			Handler:    _Person_GetPersons_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "person.proto",
}
